// Generated by Nuxt'
import type { Plugin } from '#app'

type Decorate<T extends Record<string, any>> = { [K in keyof T as K extends string ? `$${K}` : never]: T[K] }

type InjectionType<A extends Plugin> = A extends {default: Plugin<infer T>} ? Decorate<T> : unknown

type NuxtAppInjections = 
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/revive-payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/head/runtime/plugins/unhead.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/head/runtime/plugins/unhead.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/pages/runtime/plugins/router.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt-site-config@4.1.1_@nux_4abc8fd1380961a9c297d9c0f1266ac5/node_modules/nuxt-site-config/dist/runtime/app/plugins/0.siteConfig.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/payload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/navigation-repaint.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/check-outdated-build.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/revive-payload.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/chunk-reload-crawler.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/app/plugins/chunk-reload.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/pages/runtime/plugins/prefetch.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.1_ma_9f03d65aa0c3b100ecc5bf0890b7244f/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.server.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/@nuxtjs+color-mode@4.0.1_ma_9f03d65aa0c3b100ecc5bf0890b7244f/node_modules/@nuxtjs/color-mode/dist/runtime/plugin.client.js")> &
  InjectionType<typeof import("../../node_modules/.pnpm/nuxt@4.5.0_@babel+plugin-sy_a75106a48c00810e2ede7cc6d274deaf/node_modules/nuxt/dist/pages/runtime/plugins/prerender.server.js")>

declare module '#app' {
  interface NuxtApp extends NuxtAppInjections { }

  interface NuxtAppLiterals {
    pluginName: 'nuxt:revive-payload:client' | 'nuxt:head' | 'nuxt:head' | 'nuxt:router' | 'nuxt-site-config:init' | 'nuxt:payload' | 'nuxt:revive-payload:server' | 'nuxt:chunk-reload-crawler' | 'nuxt:chunk-reload' | 'nuxt:global-components' | 'nuxt:prefetch'
  }
}

declare module 'vue' {
  interface ComponentCustomProperties extends NuxtAppInjections { }
}

export { }
