// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026/7/19 22:37:05
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/codex_learn/codex_list/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/plugins/**/*.{js,ts,mjs}","C:/codex_learn/codex_list/blog/composables/**/*.{js,ts,mjs}","C:/codex_learn/codex_list/blog/utils/**/*.{js,ts,mjs}","C:/codex_learn/codex_list/blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/codex_learn/codex_list/blog/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;